name: Project Label Maker

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/project.yml'

concurrency:
  group: ci-label-issue
  cancel-in-progress: true

env:
  OWNER_NAME: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_ID: ${{ github.event.repository.node_id }}
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  SPEICIAL_COLOR: 68E0F8
  REFERENC_OWNER_NAME: cli
  REFERENC_REPO_NAME: cli
  WORKER_NAME: LABEL_INIT
  #ABC_LABEL_COLOR: 0052CC
  #ABC_LABEL_DESCRIPTION: "这是一段测试文字这个标签毫无用处" 


jobs:

  label_init:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

      #- name: 🔨 Setup .NET 6.X SDK
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '6.x'
          
    - name: 👀 PR Label Check
      run: dotnet test './test/workflow/Workflow.Runner' --nologo -c Release


