name: Issue Recommend

on:
  issues:
    types:
      - opened

env:
  OWNER_NAME: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  ISSUE_ID: ${{ github.event.issue.node_id }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  WORKER_NAME: ISSUE_RECOMMEND
  ISSUE_STATUS: ALL
  USE_PADDLE: "TRUE"

jobs:
  recommend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🔨 Setup Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - run: |
        pip install jieba
        pip install numpy

      #- name: 🔨 Setup .NET 6.X SDK
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '6.x'
          
    - name: 🌈 Recommend
      run: dotnet test './test/workflow/Workflow.Runner' --nologo -c Release


