name: PR Archive

on:
  pull_request:
    types: [closed]
    branches:
      - dev**

env:
  OWNER_NAME: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  OWNER_ID: ${{ github.event.repository.owner.node_id }}
  REPO_ID: ${{ github.event.repository.node_id }}
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.node_id }}
  PROJECT_NAME: ${{ github.event.repository.name }}_VNext
  WORKER_NAME: PR_ARCHIVE

jobs:

  archive_pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v4

      #- name: 🔨 Setup .NET 6.X SDK
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '6.x'
          
    - name: 📄 Achive PR to VNext
      run: dotnet test './test/workflow/Workflow.Runner' --nologo -c Release


