name: Label To PR

on:
  pull_request:
    types: [opened]
    branches:
      - dev**

env:
  OWNER_NAME: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_ID: ${{ github.event.repository.node_id }}
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  PR_ID: ${{ github.event.pull_request.node_id }}
  PR_NUM: ${{ github.event.pull_request.number }}
  WORKER_NAME: PR_LABEL

jobs:
    
  label_pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 🏷 Mark Label
      run: dotnet test './test/workflow/Workflow.Runner' --nologo -c Release

