name: Recommend For PR

on:
  pull_request:
    types: [opened]
    branches:
      - dev**


jobs:
    recommend:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: 🔨 Setup Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
      - run: |
          pip install jieba
          pip install numpy

      #- name: 🔨 Setup .NET 6.X SDK
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '6.x'
          
      - name: 🌈 Recommend
        run: dotnet test './test/workflow/Workflow.Runner' --nologo -c Release
        env:
          OWNER_NAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
          PR_ID: ${{ github.event.pull_request.node_id }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          WORKER_NAME: PR_RECOMMEND
          ISSUE_STATUS: OPEN
          USE_PADDLE: "TRUE"
          PICK_COUNT: 1
          MIN_SIMILAR_SCORE: 0.80
          MAX_SIMILAR_SCORE: 1
